fl.deltas~ object added
AlexHarker/FrameLib pull request #116
Opened 2023-08-30 14:35 UTC by fearn-e

Per @AlexHarker's request

Object info and help file to come later today.

Has 2 parameters to control what happens with the initial element (filled with a zero, the difference from zero, or the wrapped difference from the final element), and which direction each element compares towards.

2023-08-30 16:03 UTC, fearn-e commented
@AlexHarker I've added a help file and tidied things up now, let me know if anything needs changing!

2023-08-31 07:49 UTC, AlexHarker commented
Thanks for this! You've definitely covered most of the main variants although I'll need to think through all the cases (e.g. inputs of one / whether someone might want only the differences and hence a shorter output.

However, before that it seems inefficient to always calculate one way and then swap for the other. I would just make a functor to calculate the other way round using the stl call (and branch outside of that). As an aside looks like you try to avoid multiply zero by one. I wouldn't bother as -0 is 0. Also, marginally quicker to do a = -a rather than a *= 1.

That stuff won't be there if you make a functor but maybe useful in future to know.

2023-09-01 17:31 UTC, fearn-e commented
@AlexHarker have added all the changes discussed!

2023-09-06 17:24 UTC, AlexHarker requested changes
Some minor style things for now - I will then test for interface and correctness. Thanks!

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    case kZeroDiff:     break;
FrameLib style is to indent cases one further than the curly braces (also elsewhere)

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    if (!outSize) return;
FrameLib style is not to have single line ifs (but I don't use curly braces for one liners)

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    if (!inSize) return;
As below

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +        case kZeroFill:     break; //0
Explicitly set the output - don't rely on it being zeroed (easier to read and more reliable if the zeroing ever goes away)

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +        case kWrapDiff:     break; //0
Indent as below (also throughout)

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +        if (drop) output[0] = input[1] - input[0];
As above

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +        if (!drop) output[outSize - 1] = input[outSize - 1];
As above

2023-09-06 17:24 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    //initial element behaviour
(very picky comment) FrameLib style for comments is a space after "//" then a capital letter and then a blank line after

2023-09-07 14:08 UTC, AlexHarker requested changes
Couple more things after compiling here (and making docs)

2023-09-07 14:08 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    add("Sets the comparison direction of each element");
Missing full stop (means the xml doesn't parse correctly)

2023-09-07 14:08 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +        switch (mParameters.getEnum<Initials>(kInitial))
This switch should have a case for kDrop, or a default: break, to prevent compiler warnings and make explicit that in this case there is nothing to do.

2023-09-07 14:34 UTC, AlexHarker commented
OK - hopefully the final *code* shape change (although there will be name changes/docs clean-up).

I think there should be an additional parameter that sets whether the fill (for everything other than drop mode) is at the start or end. Right now that's tied to "compare" but I don't think that makes sense - it should be a separately controllable thing.

That will  involve futzing a little with the fill code and the iterators. Once that's done I will make suggestions for naming parameters - at the moment the names need to be thought out a little more (particularly compare as a subtraction is not a comparison, and it's hard to figure out which is "left" and which is "right" - something like "direction" and "forward" / "reverse" might be easier, but I need to think some more).

2023-09-07 17:09 UTC, fearn-e commented
> I think there should be an additional parameter that sets whether the fill (for everything other than drop mode) is at the start or end. Right now that's tied to "compare" but I don't think that makes sense - it should be a separately controllable thing.

@AlexHarker To me, the fill is picking what kind of behaviour you want for the one element that can't have a diff since there is no element before it, so I'm not 100% sure what this is requesting.

2023-09-07 17:37 UTC, AlexHarker commented
There is no specific reason for the fill to be at the start or end - you have linked this to left/right but I believe it should be a separate choice.

The two voices are then (other than the fill mode)

1 - which direction does the subtraction go
2 - where does the fill go (start or end)

Does this make sense?

2023-09-09 14:36 UTC, fearn-e commented
Got it working, just going to do some more cleanup because I think I can make it a bit neater.

2023-09-10 14:52 UTC, AlexHarker commented
Cool - I think the call to pad() could be moved out of the if structures unless I am mistaken.

2023-09-10 14:54 UTC, fearn-e commented
Yup, just did a lot of cleanup and consolidation.

2023-09-12 08:24 UTC, AlexHarker commented
OK - everything works perfectly - just some naming things and code layout that I will put in a review.

Likely I will later update the help patch a bit, but that's fine for now (there are other new objects without help files yet).

2023-09-12 08:34 UTC, AlexHarker requested changes
OK - last set of changes I hope. If necessary I will review/alter myself the wording for info later, but everything *other* than that should be mechanical to implement.

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    mParameters.addEnum(kMode, "mode", 0);
Please explicitly set a default (call one of these addEnumItem()s with an extra bool - true). By default the first in the list is used.

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    return formatInfo("Calculates the differences between adjacent values within the frame: "
Update this.

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +            return formatInfo("Input Info - details", "Input Info", verbose);
This isn't filled in

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    //TODO: FIX THESE
Complete TODO (btw - you don't need to add the name of the parameter here - that gets auto added when docs are made)

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    if (!inSize)
Add a blank line before the if()

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    if (!outSize)
Add a blank line before the if()

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    bool nudgeInput = padLocation + drop;
I think this would be better as (padLocation || drop) or more explicit still is:

(mParameters.getEnum<PaddingLocations>(kPaddingLocation) == kEnd || drop)

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.h
> +    enum Modes { kPad_In, kPad_Out, kWrap, kDrop };
Use kPadIn / kPadOut (for consistency with other code)

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.h
> +    enum ParameterList { kMode, kDirection, kPaddingLocation, kPaddingValue };
kPaddingValue -> kPadding (see the binary template)
kPaddingLocation is misnamed (because it also applies to wrap - see the cpp and make it match)

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    mParameters.addDouble(kPaddingValue, "padding_value", 0, 3);
Rename to "padding" for consistency with the binary objects)

2023-09-12 08:34 UTC, AlexHarker commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    mParameters.addEnum(kPaddingLocation, "padding_location", 2);
This doesn't apply only to padding, so "fill_position" / "fill" / "position"  would be better. In general I try to avoid underscores where I can but if you feel that "fill" or "position" is too vague the longer one is possible.

Location is fine, but it isn't used elsewhere (FrameLib_Trace uses "position" for instance - I try to keep consistent terms as far as I can, because many years of Max usage made me wish for them...

2023-09-12 11:37 UTC, fearn-e commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    bool nudgeInput = padLocation + drop;
Ah, for some reason I assumed you couldn't have an or statement like that in an assignment, thanks!

2023-09-12 11:48 UTC, fearn-e commented on FrameLib_Objects/Vector/FrameLib_Deltas.cpp
> +    mParameters.addEnum(kPaddingLocation, "padding_location", 2);
I think the underscore is worth avoiding the vagueness in this case, I'll set it to "fill_position" for now.

2023-09-13 07:35 UTC, merged